from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'add_student/$', add_student, ),
    url(r'add_destination/$',add_destination,),
    url(r'add_book/$', add_book, ),
    url(r'add_course/$',add_course,),
    url(r'add_certification/$',add_certification,),
    url(r'delete_student/$', delete_student, ),
    url(r'delete_destination/$',delete_destination,),
    url(r'delete_book/$',delete_book,),
    url(r'delete_course/$',delete_course,),
    url(r'delete_certification/$',delete_certification,),
    url(r'show_all_users', show_all_users, ),
    url(r'show_all_destinations',show_all_destinations,),
    url(r'show_all_books',show_all_books,),
    url(r'show_all_courses', show_all_courses, ),
    url(r'show_all_certifications',show_all_certifications,),
    url(r'show_one_user/$',show_one_user,),
    url(r'show_one_destination/$', show_one_destination, ),
    url(r'show_one_book/$', show_one_book, ),
    url(r'show_someone_book/$', show_someone_book, ),
    url(r'show_someone_course/$', show_someone_course, ),
    url(r'show_someone_destination/$', show_someone_destination, ),
    url(r'show_someone_certification/$', show_someone_certification, ),
    url(r'show_one_course/$', show_one_course, ),
    url(r'show_one_certification/$', show_one_certification, ),
    url(r'search_book/$', search_book, ),
    url(r'search_course/$', search_course, ),
    url(r'search_certification/$', search_certification, ),
    url(r'change_user/$', change_user, ),
    url(r'change_destination/$', change_destination, ),
    url(r'change_course/$', change_course, ),
    url(r'change_certification/$', change_certification, ),
    url(r'change_book/$', change_book, ),
    url(r'check_destination/$', check_destination, ),
    url(r'check_book/$', check_book, ),
    url(r'check_course/$', check_course, ),
    url(r'check_certification/$', check_certification, ),
    url(r'show_book/$', show_book, ),
    url(r'show_course/$', show_course, ),
    url(r'show_destination/$', show_destination, ),
    url(r'show_certification/$', show_certification, ),
]