# Generated by Django 3.2 on 2021-05-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Info',
            fields=[
                ('book_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=64)),
                ('publisher', models.CharField(max_length=64)),
                ('introduction', models.CharField(max_length=64)),
                ('ischeck', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Certification_Info',
            fields=[
                ('certification_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('certification_name', models.CharField(max_length=64)),
                ('publisher', models.CharField(max_length=64)),
                ('introduction', models.CharField(max_length=64)),
                ('ischeck', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Info',
            fields=[
                ('course_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=64)),
                ('publisher', models.CharField(max_length=64)),
                ('book', models.CharField(max_length=64)),
                ('introduction', models.CharField(max_length=64)),
                ('ischeck', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Graduation_Destination',
            fields=[
                ('user_number', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=64)),
                ('destination_info', models.CharField(max_length=64)),
                ('ischeck', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('user_number', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=64)),
                ('user_password', models.CharField(max_length=64)),
                ('user_name', models.CharField(max_length=64)),
                ('user_gender', models.CharField(max_length=64)),
                ('user_class', models.CharField(max_length=64)),
            ],
        ),
    ]
