# Generated by Django 3.2 on 2021-05-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_info',
            name='ischeck',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='certification_info',
            name='ischeck',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='course_info',
            name='ischeck',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='graduation_destination',
            name='ischeck',
            field=models.CharField(max_length=64),
        ),
    ]
