# Generated by Django 3.2 on 2021-05-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210504_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification_info',
            name='link',
            field=models.CharField(default='null', max_length=64),
        ),
    ]
