# Generated by Django 3.2 on 2021-05-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_certification_info_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_info',
            name='publisher_email',
            field=models.CharField(default='null', max_length=64),
        ),
        migrations.AddField(
            model_name='book_info',
            name='type',
            field=models.CharField(default='null', max_length=64),
        ),
        migrations.AddField(
            model_name='certification_info',
            name='publisher_email',
            field=models.CharField(default='null', max_length=64),
        ),
        migrations.AddField(
            model_name='course_info',
            name='publisher_email',
            field=models.CharField(default='null', max_length=64),
        ),
        migrations.AddField(
            model_name='course_info',
            name='teacher',
            field=models.CharField(default='null', max_length=64),
        ),
        migrations.AddField(
            model_name='course_info',
            name='type',
            field=models.CharField(default='null', max_length=64),
        ),
        migrations.AddField(
            model_name='graduation_destination',
            name='destination_department',
            field=models.CharField(default='null', max_length=64),
        ),
        migrations.AddField(
            model_name='graduation_destination',
            name='user_email',
            field=models.CharField(default='null', max_length=64),
        ),
        migrations.AlterField(
            model_name='book_info',
            name='introduction',
            field=models.CharField(default='null', max_length=64),
        ),
        migrations.AlterField(
            model_name='course_info',
            name='book',
            field=models.CharField(default='null', max_length=64),
        ),
    ]
