# Generated by Django 3.2 on 2021-05-08 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210508_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduation_destination',
            name='destination_department',
        ),
    ]
