# Generated by Django 3.2 on 2021-05-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_graduation_destination_destination_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduation_destination',
            name='type',
            field=models.CharField(default='null', max_length=64),
        ),
    ]
