# Generated by Django 3.2 on 2021-05-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_graduation_destination_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_info',
            name='user_number',
            field=models.CharField(default='null', max_length=64),
        ),
        migrations.AddField(
            model_name='certification_info',
            name='user_number',
            field=models.CharField(default='null', max_length=64),
        ),
        migrations.AddField(
            model_name='course_info',
            name='user_number',
            field=models.CharField(default='null', max_length=64),
        ),
    ]
